<?php

return array (
  'Nomina'                                                                         => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\NominaElement',
  'Nomina.Emisor'                                                                  => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\EmisorElement',
  'Nomina.Emisor.EntidadSNCF'                                                      => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Emisor\\EntidadSNCFElement',
  'Nomina.Receptor'                                                                => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\ReceptorElement',
  'Nomina.Receptor.SubContratacion.*'                                              => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Receptor\\SubContratacionElement',
  'Nomina.Percepciones'                                                            => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\PercepcionesElement',
  'Nomina.Percepciones.Percepcion.*'                                               => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\PercepcionElement',
  'Nomina.Percepciones.Percepcion.*.AccionesOTitulos'                              => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\Percepcion\\AccionesOTitulosElement',
  'Nomina.Percepciones.Percepcion.*.HorasExtra.*'                                  => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\Percepcion\\HorasExtraElement',
  'Nomina.Percepciones.JubilacionPensionRetiro'                                    => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\JubilacionPensionRetiroElement',
  'Nomina.Percepciones.SeparacionIndemnizacion'                                    => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\SeparacionIndemnizacionElement',
  'Nomina.Deducciones'                                                             => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\DeduccionesElement',
  'Nomina.Deducciones.Deduccion.*'                                                 => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Deducciones\\DeduccionElement',
  'Nomina.OtrosPagos'                                                              => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagosElement',
  'Nomina.OtrosPagos.OtroPago.*'                                                   => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPagoElement',
  'Nomina.OtrosPagos.OtroPago.*.SubsidioAlEmpleo'                                  => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPago\\SubsidioAlEmpleoElement',
  'Nomina.OtrosPagos.OtroPago.*.CompensacionSaldosAFavor'                          => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPago\\CompensacionSaldosAFavorElement',
  'Nomina.Incapacidades'                                                           => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\IncapacidadesElement',
  'Nomina.Incapacidades.Incapacidad.*'                                             => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Incapacidades\\IncapacidadElement',
  'Nomina.Receptor.SubContratacion.*.SubContratacion.*'                            => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Receptor\\SubContratacionElement',
  'Nomina.Percepciones.Percepcion.*.Percepcion.*'                                  => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\PercepcionElement',
  'Nomina.Percepciones.Percepcion.*.AccionesOTitulos.AccionesOTitulos'             => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\Percepcion\\AccionesOTitulosElement',
  'Nomina.Percepciones.Percepcion.*.HorasExtra.*.HorasExtra.*'                     => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Percepciones\\Percepcion\\HorasExtraElement',
  'Nomina.Deducciones.Deduccion.*.Deduccion.*'                                     => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Deducciones\\DeduccionElement',
  'Nomina.OtrosPagos.OtroPago.*.OtroPago.*'                                        => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPagoElement',
  'Nomina.OtrosPagos.OtroPago.*.SubsidioAlEmpleo.SubsidioAlEmpleo'                 => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPago\\SubsidioAlEmpleoElement',
  'Nomina.OtrosPagos.OtroPago.*.CompensacionSaldosAFavor.CompensacionSaldosAFavor' => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\OtrosPagos\\OtroPago\\CompensacionSaldosAFavorElement',
  'Nomina.Incapacidades.Incapacidad.*.Incapacidad.*'                               => 'App\\Containers\\Sat\\Nomina\\Values\\V12\\Elements\\Nomina\\Incapacidades\\IncapacidadElement',
);
